### ISSUE TITLE
setup.py should throw a helpful error if run on Python 2.x

### ISSUE THREAD

**Issue by toolness** [cloud-gov/django-uaa#35]
Ugh, was trying to deploy the [bug bounty dashboard](https://github.com/18F/tts-bug-bounty-dashboard/) to cloud.gov and ran into this:

```
       Collecting cg-django-uaa==1.1.0 (from -r requirements.txt (line 11))
         Downloading cg-django-uaa-1.1.0.tar.gz (1.3MB)
           Complete output from command python setup.py egg_info:
           Traceback (most recent call last):
             File "<string>", line 1, in <module>
             File "/tmp/pip-build-RTvV4h/cg-django-uaa/setup.py", line 92, in <module>
               long_description=open('README.rst', 'r', encoding='utf-8').read(),
           TypeError: 'encoding' is an invalid keyword argument for this function
```

I am guessing this may be because it is running `setup.py` with python 2.7?

**Comment by toolness** [comment]
Oh, I forgot to add a `runtime.txt` with `python-3.6.1` in it, that might fix it.

**Comment by toolness** [comment]
Yup, that fixed it!  That said, it might be good to have `setup.py` raise a more friendly error if the user runs it with Python 2.x.

**Comment by markdboyd** [comment]
This issue is stale, closing
